server:
  port: 8443
  ssl:
    key-store: /etc/letsencrypt/live/zikiza.duckdns.org/keystore.p12
    key-store-password:
    key-store-type: pkcs12
    key-alias: tomcat
    enabled: true



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/solution_challenge
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  google:
    api: ${GOOGLE_API}
  firebase:
    key: ${FIRE_KEY}
  cloud:
    gcp:
      storage:
        credentials:
          location: file:${GOOGLE_APPLICATION_CREDENTIALS}
        project-id: lunar-alpha-372905

jwt:
  header: Authorization
  secret: Z2RzYy1za2h1LWphdmEtYmFja2VuZC1qd3Qtc3R1ZHktZGVjZW1iZXItMjh0aC1oYW5naWxsZWU=
  token-validity-in-milliseconds: 86400000

bucket:
  name: zikiza

logging:
  level:
    com:
      example:
        mini_project_b: DEBUG